import React, { useEffect, useState } from 'react';
import { CheckCircle2, ChevronRight, Copy, Loader2, Check, Sparkles } from 'lucide-react';
import { ScreenId } from '../types';
import { TrustBadges } from '../components/TrustBadges';
import { submitConcierge } from '../services/api';
import { useAuthUser } from '../context/AuthContext';

interface FindCarScreenProps { onNavigate: (screen: ScreenId) => void; }
const FIND_DRAFT_KEY = 'shabaautos.find-car-draft';
const BUDGET_OPTIONS = [
  { value: 'under-20m', label: 'Under ₦20,000,000', min: 0, max: 20000000 },
  { value: '20m-35m', label: '₦20,000,000 - ₦35,000,000', min: 20000000, max: 35000000 },
  { value: '35m-50m', label: '₦35,000,000 - ₦50,000,000', min: 35000000, max: 50000000 },
  { value: '50m-80m', label: '₦50,000,000 - ₦80,000,000', min: 50000000, max: 80000000 },
  { value: 'over-80m', label: 'Above ₦80,000,000', min: 80000000, max: undefined },
];
const YEARS = ['2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'];

export const FindCarScreen: React.FC<FindCarScreenProps> = ({ onNavigate }) => {
  const { user, isLoaded, isSignedIn } = useAuthUser();
  const [carType, setCarType] = useState(''); const [make, setMake] = useState(''); const [model, setModel] = useState('');
  const [yearMin, setYearMin] = useState(''); const [yearMax, setYearMax] = useState(''); const [budget, setBudget] = useState('');
  const [fuel, setFuel] = useState(''); const [transmission, setTransmission] = useState(''); const [colorPref, setColorPref] = useState(''); const [interiorPref, setInteriorPref] = useState('');
  const [fullName, setFullName] = useState(''); const [phone, setPhone] = useState(''); const [email, setEmail] = useState(''); const [notes, setNotes] = useState('');
  const [submitted, setSubmitted] = useState(false); const [isSubmitting, setIsSubmitting] = useState(false); const [ticketId, setTicketId] = useState(''); const [submitError, setSubmitError] = useState(''); const [copiedTicket, setCopiedTicket] = useState(false);

  useEffect(() => {
    try {
      const saved = localStorage.getItem(FIND_DRAFT_KEY);
      if (saved) { const d = JSON.parse(saved); if (d && typeof d === 'object') { if (d.carType) setCarType(d.carType); if (d.make) setMake(d.make); if (d.model) setModel(d.model); if (d.yearMin) setYearMin(d.yearMin); if (d.yearMax) setYearMax(d.yearMax); if (d.budget) setBudget(d.budget); if (d.fuel) setFuel(d.fuel); if (d.transmission) setTransmission(d.transmission); if (d.colorPref) setColorPref(d.colorPref); if (d.interiorPref) setInteriorPref(d.interiorPref); if (d.fullName) setFullName(d.fullName); if (d.phone) setPhone(d.phone); if (d.email) setEmail(d.email); if (d.notes) setNotes(d.notes); } }
    } catch { /* Draft recovery is best effort. */ }
  }, []);
  useEffect(() => { if (user) { setFullName((v) => v || user.fullName || ''); setPhone((v) => v || user.phone || ''); setEmail((v) => v || user.email || ''); } }, [user]);

  const draft = () => ({ carType, make, model, yearMin, yearMax, budget, fuel, transmission, colorPref, interiorPref, fullName, phone, email, notes });
  const saveDraft = () => { try { localStorage.setItem(FIND_DRAFT_KEY, JSON.stringify(draft())); } catch { /* ignore */ } };
  const selectedBudget = BUDGET_OPTIONS.find((option) => option.value === budget);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setSubmitError('');
    if (!isLoaded) { setSubmitError('Authentication is still loading. Please try again in a moment.'); return; }
    if (!isSignedIn) { saveDraft(); onNavigate('auth'); return; }
    if (!carType || !make.trim() || !model.trim()) { setSubmitError('Select a body type and enter the make and model you want.'); return; }
    if (!yearMin || !yearMax || Number(yearMin) > Number(yearMax)) { setSubmitError('Choose a valid year range.'); return; }
    if (!selectedBudget) { setSubmitError('Choose a target budget.'); return; }
    if (!fullName.trim() || !phone.trim()) { setSubmitError('Enter your name and phone number.'); return; }
    if (!email.trim() || !/^\S+@\S+\.\S+$/.test(email)) { setSubmitError('Enter a valid email address.'); return; }
    setIsSubmitting(true);
    try {
      const payload = {
        fullName: fullName.trim(), phone: phone.trim(), email: email.trim(), bodyType: carType, make: make.trim(), model: model.trim(),
        yearRange: `${yearMin}-${yearMax}`, budgetRange: selectedBudget.label, maxBudgetNgn: selectedBudget.max ?? selectedBudget.min,
        // The API type predates these fields, but the server contract accepts them; keep
        // them structured rather than merging selections into a fragile free-text string.
        fuelType: fuel || undefined, transmission: transmission || undefined, colorPref: colorPref.trim() || undefined, interiorPref: interiorPref.trim() || undefined,
        notes: notes.trim() || undefined,
        ...({ minBudgetNgn: selectedBudget.min } as Record<string, unknown>),
      };
      const res = await submitConcierge(payload as Parameters<typeof submitConcierge>[0]);
      if (!res?.success || !res.data?.id) throw new Error(res?.message || 'Your request could not be submitted.');
      setTicketId(res.data.id); setSubmitted(true); try { localStorage.removeItem(FIND_DRAFT_KEY); } catch { /* ignore */ }
    } catch (err: any) { const message = String(err?.message || 'Your request could not be submitted. Please try again.'); setSubmitError(/401|unauthori[sz]ed|sign.?in|auth/i.test(message) ? 'Please sign in to submit. Your entries are saved on this device.' : message); saveDraft(); } finally { setIsSubmitting(false); }
  };

  return <div className="min-h-screen bg-[#f8f9fa] shaba-screen py-8"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><nav className="flex items-center gap-2 text-xs text-gray-500 mb-6"><button onClick={() => onNavigate('home')} className="hover:text-[#0a502c]">Home</button><span>&gt;</span><span className="font-semibold text-gray-900">Find a Car for Me</span></nav><div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
    <aside className="lg:col-span-3"><div className="bg-white rounded-2xl border border-gray-200 p-5 shadow-xs"><span className="inline-flex items-center gap-1 text-[11px] font-bold text-emerald-800 uppercase tracking-wider bg-emerald-50 px-2.5 py-1 rounded-full mb-3"><Sparkles className="w-3.5 h-3.5" /> Personalized concierge</span><h3 className="text-base font-black text-gray-900 mb-2">Tell us what you need</h3><p className="text-xs text-gray-500 leading-relaxed mb-4">Submit a request and an agent can confirm availability, sourcing options, inspection scope, timing, and fees before you proceed.</p><div className="space-y-2.5 text-xs text-gray-700"><div>• Market research and dealer sourcing, subject to confirmation</div><div>• Preference-based vehicle matching</div><div>• Inspection and document checks where available and agreed</div><div>• Delivery arrangements discussed separately</div></div></div></aside>
    <main className="lg:col-span-6"><div className="bg-white rounded-2xl border border-gray-200 p-6 sm:p-8 shadow-xs"><div className="mb-6"><h1 className="text-2xl font-black text-gray-900 tracking-tight">Find a Car for Me</h1><p className="text-xs sm:text-sm text-gray-600 mt-1">Describe your requirements. A submitted request is not a completed search or shortlist.</p></div><div className="grid grid-cols-4 gap-2 mb-8 pb-4 border-b border-gray-100">{['Tell Us','Review Request','Agent Follow-up','Next Steps'].map((label, i) => <div className="text-center" key={label}><div className={`h-1.5 rounded-full mb-1.5 ${i === 0 ? 'bg-[#0a502c]' : 'bg-gray-200'}`} /><span className={`text-[10px] sm:text-[11px] font-${i === 0 ? 'bold text-[#0a502c]' : 'medium text-gray-400'}`}>{i + 1}. {label}</span></div>)}</div>
      {submitted ? <div className="py-12 text-center space-y-4"><div className="w-16 h-16 rounded-full bg-emerald-100 text-[#0a502c] flex items-center justify-center mx-auto"><CheckCircle2 className="w-8 h-8" /></div><h3 className="text-xl font-bold text-gray-900">Request received</h3><div className="inline-flex items-center gap-2 bg-emerald-50 border border-emerald-200 px-4 py-2 rounded-xl text-xs text-emerald-900 font-bold"><span>Concierge ticket: <span className="font-mono text-emerald-700">{ticketId}</span></span><button type="button" onClick={() => { navigator.clipboard?.writeText(ticketId); setCopiedTicket(true); setTimeout(() => setCopiedTicket(false), 2000); }} className="p-1 hover:bg-emerald-200 rounded" title="Copy ticket ID">{copiedTicket ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}</button></div><p className="text-xs text-gray-600 max-w-md mx-auto leading-relaxed">An agent can review your {make} {model} request and contact you to confirm available options, inspection scope, timing, and any applicable fees. No shortlist, inspection report, delivery date, or price is promised by this submission.</p><div className="pt-4 flex flex-wrap justify-center gap-3"><button onClick={() => onNavigate('home')} className="px-5 py-2.5 bg-[#0a502c] text-white text-xs font-bold rounded-lg">Return home</button><button onClick={() => setSubmitted(false)} className="px-5 py-2.5 border border-gray-300 text-gray-700 text-xs font-semibold rounded-lg">Edit request</button></div></div> : <>{submitError && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-semibold text-red-800">{submitError}</div>}<form onSubmit={handleSubmit} className="space-y-6">
        <section><h3 className="text-xs font-bold text-gray-900 uppercase tracking-wider mb-3 pb-2 border-b border-gray-100">1. Vehicle requirements</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5"><div><label className="block text-xs font-bold text-gray-800 mb-1">Body type *</label><select required value={carType} onChange={(e) => setCarType(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs"><option value="">Select body type</option><option>SUV</option><option>Sedan</option><option>Hatchback</option><option>Pickup Truck</option><option>Luxury Coupe</option></select></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Make *</label><input required value={make} onChange={(e) => setMake(e.target.value)} placeholder="e.g. Toyota" className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div><div className="sm:col-span-2"><label className="block text-xs font-bold text-gray-800 mb-1">Model preference *</label><input required value={model} onChange={(e) => setModel(e.target.value)} placeholder="e.g. RAV4, Highlander, RX 350, or any model" className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Year range *</label><div className="grid grid-cols-2 gap-2"><select required value={yearMin} onChange={(e) => setYearMin(e.target.value)} className="bg-gray-50 border border-gray-300 rounded-lg px-2 py-2 text-xs"><option value="">From</option>{YEARS.map((year) => <option key={year}>{year}</option>)}</select><select required value={yearMax} onChange={(e) => setYearMax(e.target.value)} className="bg-gray-50 border border-gray-300 rounded-lg px-2 py-2 text-xs"><option value="">To</option>{YEARS.map((year) => <option key={year}>{year}</option>)}</select></div></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Target budget *</label><select required value={budget} onChange={(e) => setBudget(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs"><option value="">Select budget</option>{BUDGET_OPTIONS.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select>{selectedBudget && <p className="text-[10px] text-gray-500 mt-1">Request sends maxBudgetNgn={selectedBudget.max ?? selectedBudget.min}. The label is for display.</p>}</div></div></section>
        <section><h3 className="text-xs font-bold text-gray-900 uppercase tracking-wider mb-3 pb-2 border-b border-gray-100">2. Structured preferences</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5"><div><label className="block text-xs font-bold text-gray-800 mb-1">Fuel</label><select value={fuel} onChange={(e) => setFuel(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs"><option value="">No preference</option><option>Petrol</option><option>Diesel</option><option>Hybrid</option><option>Electric</option></select></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Transmission</label><select value={transmission} onChange={(e) => setTransmission(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs"><option value="">No preference</option><option>Automatic</option><option>Manual</option><option>CVT</option></select></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Colour preference</label><input value={colorPref} onChange={(e) => setColorPref(e.target.value)} placeholder="e.g. white or silver" className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Interior preference</label><input value={interiorPref} onChange={(e) => setInteriorPref(e.target.value)} placeholder="e.g. leather, any colour" className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div></div></section>
        <section><h3 className="text-xs font-bold text-gray-900 uppercase tracking-wider mb-3 pb-2 border-b border-gray-100">3. Contact details</h3><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div><label className="block text-xs font-bold text-gray-800 mb-1">Full name *</label><input required value={fullName} onChange={(e) => setFullName(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Phone *</label><input required type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div><div><label className="block text-xs font-bold text-gray-800 mb-1">Email *</label><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full bg-gray-50 border border-gray-300 rounded-lg px-3 py-2 text-xs" /></div></div><div className="mt-3"><label className="block text-xs font-bold text-gray-800 mb-1">Additional notes (optional)</label><textarea rows={3} maxLength={500} value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Tell us about must-have features, timing, or constraints." className="w-full bg-gray-50 border border-gray-300 rounded-lg p-2.5 text-xs" /><span className="text-[10px] text-gray-400">{notes.length}/500</span></div></section>
        {!isSignedIn && <p className="text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded-lg p-3">Sign in is required to submit. Your entries will be saved on this device and restored after sign-in.</p>}<div className="pt-4 border-t border-gray-100 flex justify-end"><button type="submit" disabled={isSubmitting} className="w-full sm:w-auto px-8 py-3 bg-[#0a502c] hover:bg-emerald-800 disabled:opacity-50 text-white font-bold text-xs rounded-xl flex items-center justify-center gap-2">{isSubmitting ? <><Loader2 className="w-4 h-4 animate-spin" /> Submitting request...</> : <>Submit request <ChevronRight className="w-4 h-4" /></>}</button></div>
      </form></>}
    </div></main>
    <aside className="lg:col-span-3 space-y-6"><div className="bg-white rounded-2xl border border-gray-200 p-5 shadow-xs"><h4 className="text-xs font-bold text-gray-900 uppercase tracking-wider mb-4 pb-2 border-b border-gray-100">What happens next</h4><div className="space-y-3.5 text-xs">{[['1','Request received','We record your requirements.'],['2','Agent follow-up','An agent confirms options and availability.'],['3','Review choices','You decide whether to proceed with any option.'],['4','Agreed next steps','Inspection, documents, fees, and delivery are confirmed separately.']].map(([n,t,c]) => <div className="flex items-start gap-2.5" key={n}><div className="w-5 h-5 rounded-full bg-emerald-50 text-[#0a502c] font-bold flex items-center justify-center text-[10px] flex-shrink-0">{n}</div><div><span className="font-bold text-gray-900">{t}</span><p className="text-[11px] text-gray-500">{c}</p></div></div>)}</div></div><div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5"><p className="text-xs text-gray-700 leading-relaxed">Service scope, inspection availability, delivery coverage, timing, and fees vary by vehicle and location and will be explained before commitment.</p></div></aside>
  </div><div className="mt-16"><TrustBadges variant="home" /></div></div></div>;
};
